unsorted_array:
	gcc -std=c89 -pedantic -Werror -Wall unsorted_array.c

sorted_array:
	gcc -O2 -std=c89 -pedantic -Werror -Wall sorted_array.c

pkcl:
	gcc -O2 -std=c89 -pedantic -Werror -Wall pkcl_test.c pkcl.c

unsorted_array_v2:
	gcc -O2 -std=c89 -pedantic -Werror -Wall pkcl.c unsorted_array_v2.c
